#!/bin/bash
#
### kasutajate lisamise skript
if [ $# -ne 1 ]; then
	echo "Kasutusjuhend :$0 failinimi"
else
  failinimi=$1
 if [ -f $failinimi -a -r $failinimi ]; then
	echo "fail on korras"
	for nimi in $(cat $failinimi)
	do
	# echo $nimi
	sh lisa_kasutaja $nimi # sellega me laseme lisa_kasutaja skripti tööle
      done
    else
	echo "probleem failiga $failinimi"
    fi
#parameetrite kontrolli lõpp
fi
