#!/bin/bash
#Kasutaja lisamine failinimest kasutades lisa_kasutaja skripti. Kasutajanimi + parool on eraldi failis

if [ $# -ne 1 ];
then
echo "Kasutusjuhend: $0 failinimi"
else
failinimi=$1
if [ -f $failinimi -a -r $failinimi ]; then
echo "Fail on korras"
for rida in $(cat $failinimi)
do
#Sellega peaks faili sisu olema nähtav, kui fail on kätte saadav ja nüüd echo asemel tuleb kutsuda vajalik skript

kasutajanimi=$(echo "$rida" | cut -f1 -d:)

sh lisa_kasutaja $kasutajanimi

echo "$rida" | chpasswd #Võimaldab kasutajale määrata vastav parool

done

else

echo "Probleem failiga $failinimi"

fi

#Parameetrite kontrolli lõpp

fi
